#include "/usr/local/include/antlr4-runtime/antlr4-runtime.h"
#include "RedoParserBaseListener.h"

#include <iostream>
#include <array> // for array, at()
#include <tuple> // for get()
using namespace std;

class change_vector {
    // Access specifier
public:
    // Data  Members
    int change_vector_id;
    string geekname;
    // Member Functions()
    void printname() { cout << "Geekname is:" << geekname; }
};

class RedoWalker : public RedoParserBaseListener
{

private:

array<change_vector,400000> change_vectors;

public:

void enterRedo_file(RedoParser::Redo_fileContext * /*ctx*/)  { std::cout << "In Redo File: "  << std::endl; }
void exitRedo_file(RedoParser::Redo_fileContext * /*ctx*/)  { }
void enterRedo_record_info(RedoParser::Redo_record_infoContext * /*ctx*/)  {std::cout << "Starting A Redo Record: "  << std::endl; }
void exitRedo_record_info(RedoParser::Redo_record_infoContext * /*ctx*/)  { }
void enterRedo_info(RedoParser::Redo_infoContext * /*ctx*/)  { }
void exitRedo_info(RedoParser::Redo_infoContext * /*ctx*/)  { }
void enterRedo_record(RedoParser::Redo_recordContext * /*ctx*/)  { }
void exitRedo_record(RedoParser::Redo_recordContext * /*ctx*/)  { }
void enterChange_records(RedoParser::Change_recordsContext * /*ctx*/)  { }
void exitChange_records(RedoParser::Change_recordsContext * /*ctx*/)  { }
void enterThread(RedoParser::ThreadContext * /*ctx*/)  { }
void exitThread(RedoParser::ThreadContext * /*ctx*/)  { }
void enterThread_number(RedoParser::Thread_numberContext * /*ctx*/)  { }
void exitThread_number(RedoParser::Thread_numberContext * /*ctx*/)  { }
void enterRba(RedoParser::RbaContext * /*ctx*/)  { }
void exitRba(RedoParser::RbaContext * /*ctx*/)  { }
void enterLog_file_sequence_number(RedoParser::Log_file_sequence_numberContext * /*ctx*/)  { }
void exitLog_file_sequence_number(RedoParser::Log_file_sequence_numberContext * /*ctx*/)  { }
void enterLog_file_block_number(RedoParser::Log_file_block_numberContext * /*ctx*/)  { }
void exitLog_file_block_number(RedoParser::Log_file_block_numberContext * /*ctx*/)  { }
void enterByte_offset(RedoParser::Byte_offsetContext * /*ctx*/)  { }
void exitByte_offset(RedoParser::Byte_offsetContext * /*ctx*/)  { }
void enterLen(RedoParser::LenContext * /*ctx*/)  { }
void exitLen(RedoParser::LenContext * /*ctx*/)  { }
void enterLen_value(RedoParser::Len_valueContext * /*ctx*/)  { }
void exitLen_value(RedoParser::Len_valueContext * /*ctx*/)  { }
void enterVld(RedoParser::VldContext * /*ctx*/)  { }
void exitVld(RedoParser::VldContext * /*ctx*/)  { }
void enterVld_value(RedoParser::Vld_valueContext * /*ctx*/)  { }
void exitVld_value(RedoParser::Vld_valueContext * /*ctx*/)  { }
void enterScn(RedoParser::ScnContext * /*ctx*/)  { }
void exitScn(RedoParser::ScnContext * /*ctx*/)  { }
void enterWrap(RedoParser::WrapContext * /*ctx*/)  { }
void exitWrap(RedoParser::WrapContext * /*ctx*/)  { }
void enterBase(RedoParser::BaseContext * /*ctx*/)  { }
void exitBase(RedoParser::BaseContext * /*ctx*/)  { }
void enterSubscn(RedoParser::SubscnContext * /*ctx*/)  { }
void exitSubscn(RedoParser::SubscnContext * /*ctx*/)  { }
void enterSubscn_value(RedoParser::Subscn_valueContext * /*ctx*/)  { }
void exitSubscn_value(RedoParser::Subscn_valueContext * /*ctx*/)  { }
void enterDate_value(RedoParser::Date_valueContext * /*ctx*/)  { }
void exitDate_value(RedoParser::Date_valueContext * /*ctx*/)  { }
void enterChg_prefix_exists(RedoParser::Chg_prefix_existsContext * /*ctx*/)  { }
void exitChg_prefix_exists(RedoParser::Chg_prefix_existsContext * /*ctx*/)  { }
void enterChange(RedoParser::ChangeContext * /*ctx*/)  { }
void exitChange(RedoParser::ChangeContext * /*ctx*/)  { }
void enterKtust_redo(RedoParser::Ktust_redoContext * /*ctx*/)  { }
void exitKtust_redo(RedoParser::Ktust_redoContext * /*ctx*/)  { }
void enterKtsfrbfmt_redo(RedoParser::Ktsfrbfmt_redoContext * /*ctx*/)  { }
void exitKtsfrbfmt_redo(RedoParser::Ktsfrbfmt_redoContext * /*ctx*/)  { }
void enterCfl(RedoParser::CflContext * /*ctx*/)  { }
void exitCfl(RedoParser::CflContext * /*ctx*/)  { }
void enterCfl_value(RedoParser::Cfl_valueContext * /*ctx*/)  { }
void exitCfl_value(RedoParser::Cfl_valueContext * /*ctx*/)  { }
void enterCscn(RedoParser::CscnContext * /*ctx*/)  { }
void exitCscn(RedoParser::CscnContext * /*ctx*/)  { }
void enterCscn_value(RedoParser::Cscn_valueContext * /*ctx*/)  { }
void exitCscn_value(RedoParser::Cscn_valueContext * /*ctx*/)  { }
void enterItls(RedoParser::ItlsContext * /*ctx*/)  { }
void exitItls(RedoParser::ItlsContext * /*ctx*/)  { }
void enterItls_value(RedoParser::Itls_valueContext * /*ctx*/)  { }
void exitItls_value(RedoParser::Itls_valueContext * /*ctx*/)  { }
void enterTyp(RedoParser::TypContext * /*ctx*/)  { }
void exitTyp(RedoParser::TypContext * /*ctx*/)  { }
void enterTyp_value(RedoParser::Typ_valueContext * /*ctx*/)  { }
void exitTyp_value(RedoParser::Typ_valueContext * /*ctx*/)  { }
void enterType(RedoParser::TypeContext * /*ctx*/)  { }
void exitType(RedoParser::TypeContext * /*ctx*/)  { }
void enterType_value(RedoParser::Type_valueContext * /*ctx*/)  { }
void exitType_value(RedoParser::Type_valueContext * /*ctx*/)  { }
void enterSegobjd(RedoParser::SegobjdContext * /*ctx*/)  { }
void exitSegobjd(RedoParser::SegobjdContext * /*ctx*/)  { }
void enterSegobjd_value(RedoParser::Segobjd_valueContext * /*ctx*/)  { }
void exitSegobjd_value(RedoParser::Segobjd_valueContext * /*ctx*/)  { }
void enterKtsfm_redo(RedoParser::Ktsfm_redoContext * /*ctx*/)  { }
void exitKtsfm_redo(RedoParser::Ktsfm_redoContext * /*ctx*/)  { }
void enterNfl(RedoParser::NflContext * /*ctx*/)  { }
void exitNfl(RedoParser::NflContext * /*ctx*/)  { }
void enterNfl_value(RedoParser::Nfl_valueContext * /*ctx*/)  { }
void exitNfl_value(RedoParser::Nfl_valueContext * /*ctx*/)  { }
void enterKtsfrblnk_redo(RedoParser::Ktsfrblnk_redoContext * /*ctx*/)  { }
void exitKtsfrblnk_redo(RedoParser::Ktsfrblnk_redoContext * /*ctx*/)  { }
void enterKtsfrblnk_redo_opcode(RedoParser::Ktsfrblnk_redo_opcodeContext * /*ctx*/)  { }
void exitKtsfrblnk_redo_opcode(RedoParser::Ktsfrblnk_redo_opcodeContext * /*ctx*/)  { }
void enterKtucm_redo(RedoParser::Ktucm_redoContext * /*ctx*/)  { }
void exitKtucm_redo(RedoParser::Ktucm_redoContext * /*ctx*/)  { }
void enterKtucf_redo(RedoParser::Ktucf_redoContext * /*ctx*/)  { }
void exitKtucf_redo(RedoParser::Ktucf_redoContext * /*ctx*/)  { }
void enterExt(RedoParser::ExtContext * /*ctx*/)  { }
void exitExt(RedoParser::ExtContext * /*ctx*/)  { }
void enterExt_value(RedoParser::Ext_valueContext * /*ctx*/)  { }
void exitExt_value(RedoParser::Ext_valueContext * /*ctx*/)  { }
void enterUba(RedoParser::UbaContext * /*ctx*/)  { }
void exitUba(RedoParser::UbaContext * /*ctx*/)  { }
void enterUba_value(RedoParser::Uba_valueContext * /*ctx*/)  { }
void exitUba_value(RedoParser::Uba_valueContext * /*ctx*/)  { }
void enterSta(RedoParser::StaContext * /*ctx*/)  { }
void exitSta(RedoParser::StaContext * /*ctx*/)  { }
void enterSta_value(RedoParser::Sta_valueContext * /*ctx*/)  { }
void exitSta_value(RedoParser::Sta_valueContext * /*ctx*/)  { }
void enterSrt(RedoParser::SrtContext * /*ctx*/)  { }
void exitSrt(RedoParser::SrtContext * /*ctx*/)  { }
void enterSrt_value(RedoParser::Srt_valueContext * /*ctx*/)  { }
void exitSrt_value(RedoParser::Srt_valueContext * /*ctx*/)  { }
void enterKtecush_redo(RedoParser::Ktecush_redoContext * /*ctx*/)  { }
void exitKtecush_redo(RedoParser::Ktecush_redoContext * /*ctx*/)  { }
void enterKtsfrgrp_redo(RedoParser::Ktsfrgrp_redoContext * /*ctx*/)  { }
void exitKtsfrgrp_redo(RedoParser::Ktsfrgrp_redoContext * /*ctx*/)  { }
void enterKtubl_redo(RedoParser::Ktubl_redoContext * /*ctx*/)  { }
void exitKtubl_redo(RedoParser::Ktubl_redoContext * /*ctx*/)  { }
void enterKtubu_redo(RedoParser::Ktubu_redoContext * /*ctx*/)  { }
void exitKtubu_redo(RedoParser::Ktubu_redoContext * /*ctx*/)  { }
void enterKtelk_redo(RedoParser::Ktelk_redoContext * /*ctx*/)  { }
void exitKtelk_redo(RedoParser::Ktelk_redoContext * /*ctx*/)  { }
void enterKtudb_redo(RedoParser::Ktudb_redoContext * /*ctx*/)  { }
void exitKtudb_redo(RedoParser::Ktudb_redoContext * /*ctx*/)  { }
void enterKtudbu_redo(RedoParser::Ktudbu_redoContext * /*ctx*/)  { }
void exitKtudbu_redo(RedoParser::Ktudbu_redoContext * /*ctx*/)  { }
void enterObj(RedoParser::ObjContext * /*ctx*/)  { }
void exitObj(RedoParser::ObjContext * /*ctx*/)  { }
void enterObjn(RedoParser::ObjnContext * /*ctx*/)  { }
void exitObjn(RedoParser::ObjnContext * /*ctx*/)  { }
void enterObjn_value(RedoParser::Objn_valueContext * /*ctx*/)  { }
void exitObjn_value(RedoParser::Objn_valueContext * /*ctx*/)  { }
void enterObjd(RedoParser::ObjdContext * /*ctx*/)  { }
void exitObjd(RedoParser::ObjdContext * /*ctx*/)  { }
void enterObjd_value(RedoParser::Objd_valueContext * /*ctx*/)  { }
void exitObjd_value(RedoParser::Objd_valueContext * /*ctx*/)  { }
void enterTsn(RedoParser::TsnContext * /*ctx*/)  { }
void exitTsn(RedoParser::TsnContext * /*ctx*/)  { }
void enterTsn_value(RedoParser::Tsn_valueContext * /*ctx*/)  { }
void exitTsn_value(RedoParser::Tsn_valueContext * /*ctx*/)  { }
void enterOpc(RedoParser::OpcContext * /*ctx*/)  { }
void exitOpc(RedoParser::OpcContext * /*ctx*/)  { }
void enterOpc_value(RedoParser::Opc_valueContext * /*ctx*/)  { }
void exitOpc_value(RedoParser::Opc_valueContext * /*ctx*/)  { }
void enterKtudh_redo(RedoParser::Ktudh_redoContext * /*ctx*/)  { }
void exitKtudh_redo(RedoParser::Ktudh_redoContext * /*ctx*/)  { }
void enterFbi(RedoParser::FbiContext * /*ctx*/)  { }
void exitFbi(RedoParser::FbiContext * /*ctx*/)  { }
void enterFbi_value(RedoParser::Fbi_valueContext * /*ctx*/)  { }
void exitFbi_value(RedoParser::Fbi_valueContext * /*ctx*/)  { }
void enterSiz(RedoParser::SizContext * /*ctx*/)  { }
void exitSiz(RedoParser::SizContext * /*ctx*/)  { }
void enterSiz_value(RedoParser::Siz_valueContext * /*ctx*/)  { }
void exitSiz_value(RedoParser::Siz_valueContext * /*ctx*/)  { }
void enterSqn(RedoParser::SqnContext * /*ctx*/)  { }
void exitSqn(RedoParser::SqnContext * /*ctx*/)  { }
void enterSqn_value(RedoParser::Sqn_valueContext * /*ctx*/)  { }
void exitSqn_value(RedoParser::Sqn_valueContext * /*ctx*/)  { }
void enterSpc(RedoParser::SpcContext * /*ctx*/)  { }
void exitSpc(RedoParser::SpcContext * /*ctx*/)  { }
void enterSpc_value(RedoParser::Spc_valueContext * /*ctx*/)  { }
void exitSpc_value(RedoParser::Spc_valueContext * /*ctx*/)  { }
void enterRec(RedoParser::RecContext * /*ctx*/)  { }
void exitRec(RedoParser::RecContext * /*ctx*/)  { }
void enterRec_value(RedoParser::Rec_valueContext * /*ctx*/)  { }
void exitRec_value(RedoParser::Rec_valueContext * /*ctx*/)  { }
void enterRci(RedoParser::RciContext * /*ctx*/)  { }
void exitRci(RedoParser::RciContext * /*ctx*/)  { }
void enterRci_value(RedoParser::Rci_valueContext * /*ctx*/)  { }
void exitRci_value(RedoParser::Rci_valueContext * /*ctx*/)  { }
void enterSlt(RedoParser::SltContext * /*ctx*/)  { }
void exitSlt(RedoParser::SltContext * /*ctx*/)  { }
void enterSlt_value(RedoParser::Slt_valueContext * /*ctx*/)  { }
void exitSlt_value(RedoParser::Slt_valueContext * /*ctx*/)  { }
void enterInvld(RedoParser::InvldContext * /*ctx*/)  { }
void exitInvld(RedoParser::InvldContext * /*ctx*/)  { }
void enterMedia_recovery_marker(RedoParser::Media_recovery_markerContext * /*ctx*/)  { }
void exitMedia_recovery_marker(RedoParser::Media_recovery_markerContext * /*ctx*/)  { }
void enterChange_number(RedoParser::Change_numberContext * /*ctx*/)  { }
void exitChange_number(RedoParser::Change_numberContext * /*ctx*/)  { }
void enterBlks(RedoParser::BlksContext * /*ctx*/)  { }
void exitBlks(RedoParser::BlksContext * /*ctx*/)  { }
void enterBlks_value(RedoParser::Blks_valueContext * /*ctx*/)  { }
void exitBlks_value(RedoParser::Blks_valueContext * /*ctx*/)  { }
void enterChg_type(RedoParser::Chg_typeContext * /*ctx*/)  { }
void exitChg_type(RedoParser::Chg_typeContext * /*ctx*/)  { }
void enterChg_type_value(RedoParser::Chg_type_valueContext * /*ctx*/)  { }
void exitChg_type_value(RedoParser::Chg_type_valueContext * /*ctx*/)  { }
void enterChg_class(RedoParser::Chg_classContext * /*ctx*/)  { }
void exitChg_class(RedoParser::Chg_classContext * /*ctx*/)  { }
void enterChg_class_value(RedoParser::Chg_class_valueContext * /*ctx*/)  { }
void exitChg_class_value(RedoParser::Chg_class_valueContext * /*ctx*/)  { }
void enterChg_afn(RedoParser::Chg_afnContext * /*ctx*/)  { }
void exitChg_afn(RedoParser::Chg_afnContext * /*ctx*/)  { }
void enterAfn_value(RedoParser::Afn_valueContext * /*ctx*/)  { }
void exitAfn_value(RedoParser::Afn_valueContext * /*ctx*/)  { }
void enterDba(RedoParser::DbaContext * /*ctx*/)  { }
void exitDba(RedoParser::DbaContext * /*ctx*/)  { }
void enterDba_value(RedoParser::Dba_valueContext * /*ctx*/)  { }
void exitDba_value(RedoParser::Dba_valueContext * /*ctx*/)  { }
void enterChg_obj(RedoParser::Chg_objContext * /*ctx*/)  { }
void exitChg_obj(RedoParser::Chg_objContext * /*ctx*/)  { }
void enterObj_value(RedoParser::Obj_valueContext * /*ctx*/)  { }
void exitObj_value(RedoParser::Obj_valueContext * /*ctx*/)  { }
void enterSeq(RedoParser::SeqContext * /*ctx*/)  { }
void exitSeq(RedoParser::SeqContext * /*ctx*/)  { }
void enterSeq_value(RedoParser::Seq_valueContext * /*ctx*/)  { }
void exitSeq_value(RedoParser::Seq_valueContext * /*ctx*/)  { }
void enterXid(RedoParser::XidContext * /*ctx*/)  { }
void exitXid(RedoParser::XidContext * /*ctx*/)  { }
void enterXid_value(RedoParser::Xid_valueContext * /*ctx*/)  { }
void exitXid_value(RedoParser::Xid_valueContext * /*ctx*/)  { }
void enterLayer_opcode(RedoParser::Layer_opcodeContext * /*ctx*/)  { }
void exitLayer_opcode(RedoParser::Layer_opcodeContext * /*ctx*/)  { }
void enterLayer(RedoParser::LayerContext * /*ctx*/)  { }
void exitLayer(RedoParser::LayerContext * /*ctx*/)  { }
void enterOpcode(RedoParser::OpcodeContext * /*ctx*/)  { }
void exitOpcode(RedoParser::OpcodeContext * /*ctx*/)  { }
void enterEnc(RedoParser::EncContext * /*ctx*/)  { }
void exitEnc(RedoParser::EncContext * /*ctx*/)  { }
void enterEnc_value(RedoParser::Enc_valueContext * /*ctx*/)  { }
void exitEnc_value(RedoParser::Enc_valueContext * /*ctx*/)  { }
void enterRbl(RedoParser::RblContext * /*ctx*/)  { }
void exitRbl(RedoParser::RblContext * /*ctx*/)  { }
void enterRbl_value(RedoParser::Rbl_valueContext * /*ctx*/)  { }
void exitRbl_value(RedoParser::Rbl_valueContext * /*ctx*/)  { }
void enterFlg(RedoParser::FlgContext * /*ctx*/)  { }
void exitFlg(RedoParser::FlgContext * /*ctx*/)  { }
void enterFlg_value(RedoParser::Flg_valueContext * /*ctx*/)  { }
void exitFlg_value(RedoParser::Flg_valueContext * /*ctx*/)  { }
void enterCon_id(RedoParser::Con_idContext * /*ctx*/)  { }
void exitCon_id(RedoParser::Con_idContext * /*ctx*/)  { }
void enterCon_id_value(RedoParser::Con_id_valueContext * /*ctx*/)  { }
void exitCon_id_value(RedoParser::Con_id_valueContext * /*ctx*/)  { }
void enterCon_uid(RedoParser::Con_uidContext * /*ctx*/)  { }
void exitCon_uid(RedoParser::Con_uidContext * /*ctx*/)  { }
void enterCon_uid_value(RedoParser::Con_uid_valueContext * /*ctx*/)  { }
void exitCon_uid_value(RedoParser::Con_uid_valueContext * /*ctx*/)  { }
void enterColumn_info(RedoParser::Column_infoContext * /*ctx*/)  { }
void exitColumn_info(RedoParser::Column_infoContext * /*ctx*/)  { }
void enterColumn_info_detail(RedoParser::Column_info_detailContext * /*ctx*/)  { }
void exitColumn_info_detail(RedoParser::Column_info_detailContext * /*ctx*/)  { }
void enterColumn_datatype(RedoParser::Column_datatypeContext * /*ctx*/)  { }
void exitColumn_datatype(RedoParser::Column_datatypeContext * /*ctx*/)  { }
void enterColumn_number(RedoParser::Column_numberContext * /*ctx*/)  { }
void exitColumn_number(RedoParser::Column_numberContext * /*ctx*/)  { }
void enterColumn_value(RedoParser::Column_valueContext * /*ctx*/)  { }
void exitColumn_value(RedoParser::Column_valueContext * /*ctx*/)  { }
void enterBlock_cleanout_record(RedoParser::Block_cleanout_recordContext * /*ctx*/)  { }
void exitBlock_cleanout_record(RedoParser::Block_cleanout_recordContext * /*ctx*/)  { }
void enterOpt(RedoParser::OptContext * /*ctx*/)  { }
void exitOpt(RedoParser::OptContext * /*ctx*/)  { }
void enterOpt_value(RedoParser::Opt_valueContext * /*ctx*/)  { }
void exitOpt_value(RedoParser::Opt_valueContext * /*ctx*/)  { }
void enterVer(RedoParser::VerContext * /*ctx*/)  { }
void exitVer(RedoParser::VerContext * /*ctx*/)  { }
void enterVer_value(RedoParser::Ver_valueContext * /*ctx*/)  { }
void exitVer_value(RedoParser::Ver_valueContext * /*ctx*/)  { }
void enterBigscn(RedoParser::BigscnContext * /*ctx*/)  { }
void exitBigscn(RedoParser::BigscnContext * /*ctx*/)  { }
void enterCompact(RedoParser::CompactContext * /*ctx*/)  { }
void exitCompact(RedoParser::CompactContext * /*ctx*/)  { }
void enterSpare(RedoParser::SpareContext * /*ctx*/)  { }
void exitSpare(RedoParser::SpareContext * /*ctx*/)  { }
void enterSpare_value(RedoParser::Spare_valueContext * /*ctx*/)  { }
void exitSpare_value(RedoParser::Spare_valueContext * /*ctx*/)  { }
void enterLfdba(RedoParser::LfdbaContext * /*ctx*/)  { }
void exitLfdba(RedoParser::LfdbaContext * /*ctx*/)  { }
void enterLfdba_value(RedoParser::Lfdba_valueContext * /*ctx*/)  { }
void exitLfdba_value(RedoParser::Lfdba_valueContext * /*ctx*/)  { }
void enterDatafile_resize_marker(RedoParser::Datafile_resize_markerContext * /*ctx*/)  { }
void exitDatafile_resize_marker(RedoParser::Datafile_resize_markerContext * /*ctx*/)  { }
void enterFile(RedoParser::FileContext * /*ctx*/)  { }
void exitFile(RedoParser::FileContext * /*ctx*/)  { }
void enterFile_value(RedoParser::File_valueContext * /*ctx*/)  { }
void exitFile_value(RedoParser::File_valueContext * /*ctx*/)  { }
void enterOld_size(RedoParser::Old_sizeContext * /*ctx*/)  { }
void exitOld_size(RedoParser::Old_sizeContext * /*ctx*/)  { }
void enterOld_size_value(RedoParser::Old_size_valueContext * /*ctx*/)  { }
void exitOld_size_value(RedoParser::Old_size_valueContext * /*ctx*/)  { }
void enterNew_size(RedoParser::New_sizeContext * /*ctx*/)  { }
void exitNew_size(RedoParser::New_sizeContext * /*ctx*/)  { }
void enterNew_size_value(RedoParser::New_size_valueContext * /*ctx*/)  { }
void exitNew_size_value(RedoParser::New_size_valueContext * /*ctx*/)  { }
void enterEveryRule(antlr4::ParserRuleContext * /*ctx*/)  { }
void exitEveryRule(antlr4::ParserRuleContext * /*ctx*/)  { }
void visitTerminal(antlr4::tree::TerminalNode * /*node*/)  { }
void visitErrorNode(antlr4::tree::ErrorNode * /*node*/)  { }
};

